### ISSUE TITLE
Bug: not using shadow root with LitElement is causing "Slot Rendering Timeout" error

### ISSUE THREAD

**Issue by willsteinmetzfmr** [EightShapes/lit-element-mixins#24]
We're currently using Slotify with LitElement and have run into a problem. It is working in a component that shadow root still enabled but when we override LitElement to not include it by adding `createRenderRoot() { return this; }` to the component class, the "Slot Rendering Timeout" error is thrown. We were able to test this out by having a very simple component with a simple template of `<div><s-slot name="extra"></s-slot></div>` both with and without the createRenderRoot() method. Without the method, it worked fine. With the method, it threw the above error.

I'm not sure where to go from here but happy to provide other info if it will be helpful in debugging this problem.

**Comment by willsteinmetzfmr** [comment]
@kevinmpowell any thoughts on this?

**Comment by kevinmpowell** [comment]
@willsteinmetzfmr Slotify utilizes the `createRenderRoot` method to override the default LitElement behavior.  See: https://github.com/EightShapes/lit-element-mixins/blob/master/packages/slotify/src/slotify.js#L214

I'm a little confused about what you're trying to accomplish? Do you want to use Slotify with the ShadowDOM?

**Comment by willsteinmetzfmr** [comment]
No, we're trying to use Slotify without the ShadownDOM. So it sounds like don't include a `createRenderRoot` in the component using Slotify as it will be automatically added?

**Comment by kevinmpowell** [comment]
> don't include a `createRenderRoot` in the component using Slotify as it will be automatically added

That's correct.

**Comment by willsteinmetzfmr** [comment]
Argh, not sure how I missed that 🤦 Thanks for clarifying and sorry for the confusion!

**Comment by kevinmpowell** [comment]
NP!
