### ISSUE TITLE
Ignore comment nodes and whitespace in `hasSlotableContent`

### ISSUE THREAD

**Issue by dayton-bobbitt** [EightShapes/lit-element-mixins#30]
Hey @kevinmpowell!

## Some background
We've been using Slotify's `hasSlotableContent` method to inspect the DOM before initial render and determine if a consumer is using slots.

## The problem
Recently we've noticed that `hasSlotableContent` will return `true` when checking the `default` slot for slotable content when it should be returning `false`. Upon inspection, it seems that the issue occurs when comment nodes and whitespace exist.

For example, I would expect calling `hasSlotableContent()` on the following component to return `false` because nothing is slotted in the `default` slot; however, the method returns `true` because of whitespace being interpretted as slotted content.

```html
<my-cheeseburger>
    <div slot="bun-bottom">BUN BOTTOM</div>
    <div slot="bun-top">BUN TOP</div>
    <div slot="cheese">CHEESE</div>
</my-cheeseburger>
```

## Proposed solution
Add an additional argument to `hasSlotableContent` that allows users to configure whether or not to count comment nodes and whitespace as slotted content.

```javascript
hasSlotableContent(slotName = 'default', options = { ignoreComments: false, ignoreWhitespace: false }) {
    // ...some logic to optionally filter out comments and whitespace before returning true / false
}
```

In order to avoid breaking change, the default `options` can be configured so that the `hasSlotableContent` method continues to behave as it currently does.

*I'm willing to author some failing test cases and author the PR for this feature enhancement. This issue is meant to start the conversation and act as a heads up.*

**Comment by kevinmpowell** [comment]
@dayton-bobbitt I like this an option flag that's off by default. That reflects the way true ShadowDOM slots work. In the spec, ShadowDOM will interpret whitespace in slots as slotable content which is why Slotify works the way it does.

**Comment by dayton-bobbitt** [comment]
Thanks! I'll start working on a PR then.

What are your thoughts on including a similar `hasAssignedSlotContent` method that behaves just like `hasSlotableContent` but for post-render checking? Using these methods together would allow a component to ask "is this slot being used at all" regardless of whether or not it has been rendered.

**Comment by kevinmpowell** [comment]
> What are your thoughts on including a similar `hasAssignedSlotContent` method that behaves just like `hasSlotableContent` but for post-render checking? Using these methods together would allow a component to ask "is this slot being used at all" regardless of whether or not it has been rendered.

👍
